version: "2"
services:
    web:
        build: .
        links:
            - "db:mysql"
        volumes:
            - "./app:/var/www/html"
    nginx:
        build: nginx/
        ports:
            - "80:8080"
        links:
            - "web"
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf"
    db:
        image: mysql
        volumes_from:
            - dataonly
        environment:
            MYSQL_ROOT_PASSWORD: password
    dataonly:
        image: busybox
        volumes:
            - "/var/lib/mysql"
